name: Test Repo Reference
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: Qualifyze/check-git-integrity-action@v1
